export const items = [
    "acacia_boat", "amethyst_shard", "apple", "armor_stand", "arrow", "axolotl_bucket",
    "baked_potato", "bamboo", "barrel", "barrier", "beacon", "bedrock", "beef", "bell",
    "birch_boat", "blaze_powder", "blaze_rod", "bone", "bone_meal", "book", "bow", "bowl",
    "bread", "brewing_stand", "brick", "bucket", "bundle", "cake", "campfire", "carrot",
    "carrot_on_a_stick", "cat_spawn_egg", "cauldron", "chainmail_boots", "chainmail_chestplate",
    "chainmail_helmet", "chainmail_leggings", "charcoal", "chest", "chest_minecart", "chicken",
    "chicken_spawn_egg", "chorus_fruit", "clay_ball", "clock", "coal", "cobblestone", "cod",
    "cod_bucket", "command_block", "comparator", "compass", "cooked_beef", "cooked_chicken",
    "cooked_cod", "cooked_mutton", "cooked_porkchop", "cooked_rabbit", "cooked_salmon", "cookie",
    "copper_ingot", "cow_spawn_egg", "creeper_head", "creeper_spawn_egg", "crossbow", "diamond",
    "diamond_axe", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_hoe",
    "diamond_horse_armor", "diamond_leggings", "diamond_pickaxe", "diamond_shovel", "diamond_sword",
    "dragon_breath", "dragon_egg", "dragon_head", "dried_kelp", "egg", "elytra", "emerald",
    "enchanted_book", "enchanted_golden_apple", "end_crystal", "ender_eye", "ender_pearl",
    "enderman_spawn_egg", "experience_bottle", "feather", "fermented_spider_eye", "fire_charge",
    "firework_rocket", "firework_star", "fishing_rod", "flint", "flint_and_steel", "flower_pot",
    "furnace", "ghast_tear", "glass_bottle", "glistering_melon_slice", "glow_berries",
    "glow_ink_sac", "glow_item_frame", "glowstone_dust", "goat_horn", "gold_ingot", "gold_nugget",
    "golden_apple", "golden_axe", "golden_boots", "golden_carrot", "golden_chestplate",
    "golden_helmet", "golden_hoe", "golden_horse_armor", "golden_leggings", "golden_pickaxe",
    "golden_shovel", "golden_sword", "grass_block", "gunpowder", "heart_of_the_sea",
    "honey_bottle", "honeycomb", "hopper", "hopper_minecart", "horse_spawn_egg", "ink_sac",
    "iron_axe", "iron_boots", "iron_chestplate", "iron_door", "iron_helmet", "iron_hoe",
    "iron_horse_armor", "iron_ingot", "iron_leggings", "iron_nugget", "iron_pickaxe",
    "iron_shovel", "iron_sword", "item_frame", "lantern", "lapis_lazuli", "lava_bucket", "lead",
    "leather", "leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings",
    "lever", "lily_pad", "magma_cream", "map", "melon_slice", "milk_bucket", "minecart",
    "mojang_banner_pattern", "mushroom_stew", "music_disc_11", "music_disc_13", "music_disc_cat",
    "music_disc_chirp", "music_disc_pigstep", "mutton", "name_tag", "nautilus_shell",
    "nether_brick", "nether_star", "nether_wart", "netherite_axe", "netherite_boots",
    "netherite_chestplate", "netherite_helmet", "netherite_hoe", "netherite_ingot",
    "netherite_leggings", "netherite_pickaxe", "netherite_scrap", "netherite_shovel",
    "netherite_sword", "oak_boat", "obsidian", "painting", "paper", "phantom_membrane",
    "pig_spawn_egg", "porkchop", "potato", "potion", "prismarine_crystals", "prismarine_shard",
    "pufferfish", "pufferfish_bucket", "pumpkin_pie", "quartz", "rabbit", "rabbit_foot",
    "rabbit_hide", "rabbit_stew", "rail", "redstone", "redstone_lamp", "redstone_torch",
    "repeater", "rotten_flesh", "saddle", "salmon", "salmon_bucket", "scute", "shears",
    "sheep_spawn_egg", "shield", "shulker_shell", "skeleton_skull", "slime_ball", "snowball",
    "soul_lantern", "spider_eye", "spyglass", "stick", "stone_axe", "stone_boots",
    "stone_chestplate", "stone_helmet", "stone_hoe", "stone_leggings", "stone_pickaxe",
    "stone_shovel", "stone_sword", "string", "sugar", "sugar_cane", "suspicious_stew",
    "sweet_berries", "tnt", "tnt_minecart", "torch", "totem_of_undying", "trident", "tripwire_hook",
    "tropical_fish", "tropical_fish_bucket", "turtle_helmet", "villager_spawn_egg", "water_bucket",
    "wheat", "wheat_seeds", "white_wool", "wither_skeleton_skull", "wolf_spawn_egg",
    "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel", "wooden_sword",
    "writable_book", "written_book", "zombie_head"
];
